language: python
# vesions
python:
  - "2.7.13"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nosetests
  - pip install coverage
# command to run tests
script:
  - nosetests

after_success:
  - coveralls
